import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/main-nav";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QQ Ticket Application",
  description: "Generated by sunqq2008@qq.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div>
              <nav className="flex flex-col items-center border-b mb-3 p-3">
                <div className="max-w-6xl w-full">
                  <MainNav />
                </div>
              </nav>
              <main className="flex flex-col items-center">
                <div className="max-w-6xl w-full">{children}</div>
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
